# Generated by Django 4.1.3 on 2022-12-07 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_communication_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationfile',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comfiles', to='contact.communication'),
        ),
    ]
