# Generated by Django 4.1.3 on 2022-12-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_communicationfile_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='category',
            field=models.ManyToManyField(related_name='category', to='contact.categoryproblem', verbose_name='category'),
        ),
    ]
