# Generated by Django 4.1.3 on 2022-12-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_communication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='communication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='contact.communication'),
            preserve_default=False,
        ),
    ]
