# Generated by Django 4.1.3 on 2022-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_chat_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='lat_cord',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
        migrations.AlterField(
            model_name='communication',
            name='long_cord',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
        migrations.AlterField(
            model_name='communication',
            name='number_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
