# Generated by Django 4.1.3 on 2022-12-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_communication_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='lat_cord',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='communication',
            name='long_cord',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
