# Generated by Django 4.1.3 on 2022-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_communication_lat_cord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='from_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='to_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_user',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
